### ISSUE TITLE
Add directional position utilities

### ISSUE THREAD

**Issue by sebnitu** [sebnitu/vrembem#658]
## Problem

With the addition of the position utilities, there's a need to be able to set their top, right, bottom and left positions using utilities as well. The most basic example would be to set those values to `0`. So we can use the following and not need additional CSS:

```html
<div class="position-sticky top">...</div>
```

```css
.output {
  position: sticky;
  top: 0;
}
```
