### ISSUE TITLE
Add border style utilities

### ISSUE THREAD

**Issue by sebnitu** [sebnitu/vrembem#851]
## What changed?

Sometimes we need to update the border style using utilities:

```scss
.border-style-dotted {
  border-style: dotted !important;
}

.border-style-dashed {
  border-style: dashed !important;
}
```
